version: '3'

services:
  backend:
    build: ./backend
    depends_on:
      - mongo
    env_file: 
      - ./env/backend.env
    ports:
      - "80:80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  front:
    build: ./frontend
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    depends_on: 
      - backend